### ISSUE TITLE
Hero on home page should change to COVID-19 campaign image

### ISSUE THREAD

**Issue by knice** [ucsc/site-giving#33]
@Mirandapow will provide image by uploading it to a comment on this issue.

**Comment by Mirandapow** [comment]
Hi Jason, 

I am sharing two versions of the homepage image. Since we usually like to add the copy in as type and not as a graphic, I included both since I wasn't sure how you wanted to move forward with that. If you do want to add the type, here are the specs:
"COVID-19" in white, Roboto Bold, point size 167
"Slug Support Campaign" in gold, Roboto Light, point size 167
![COVID-19_Support_648x291-01](https://user-images.githubusercontent.com/60756584/80751045-f28db480-8add-11ea-9895-a03f6b02450f.jpg)
![type-01](https://user-images.githubusercontent.com/60756584/80751050-f3bee180-8add-11ea-9586-33138505aaef.jpg)

**Comment by Herm71** [comment]
Done!
